import os from 'node:os';
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { baseDir, logsDir } from '../config/paths.js';

/**
 * OS-level daemon install — makes the daemon run at login and restart on crash.
 * Modeled on the newra daemon (launchd RunAtLoad + KeepAlive) and mailman's
 * scheduler/ticker-install.ts (the launchd/systemd PATH gotcha). See
 * docs/CROSS-OS.md for the per-OS mechanism matrix and docs/SECURITY.md
 * (never root; user-domain agents/units).
 *
 * File generation is separated from the load/unload step so the plist/unit
 * text is unit-testable, and `daemon install --print` can show exactly what
 * would be written/loaded without mutating the system.
 */

export type Mechanism = 'launchd' | 'systemd' | 'openrc' | 'nohup' | 'schtasks';

function commandExists(cmd: string): boolean {
  try {
    execFileSync(process.platform === 'win32' ? 'where' : 'which', [cmd], { stdio: 'ignore' });
    return true;
  } catch {
    return false;
  }
}

function hasSystemdUser(): boolean {
  // systemctl present AND a user D-Bus session is plausible.
  return commandExists('systemctl');
}

export function detectMechanism(): Mechanism {
  if (process.platform === 'darwin') return 'launchd';
  if (process.platform === 'win32') return 'schtasks';
  if (hasSystemdUser()) return 'systemd';
  if (commandExists('rc-service')) return 'openrc';
  return 'nohup';
}

/** whatsappman-<hostname slug>. Stable per machine; used for the job label/name. */
export function hostSlug(host: string = os.hostname()): string {
  const slug = host
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 40);
  return slug || 'local';
}

export function instanceId(host?: string): string {
  return `whatsappman-${hostSlug(host)}`;
}

export function launchdLabel(host?: string): string {
  return `com.indianic.whatsappman.${hostSlug(host)}`;
}

export function launcherPath(): string {
  return path.join(baseDir(), 'bin', `whatsappmand-${hostSlug()}`);
}

/** The built entrypoint (dist/index.js) the launcher/unit invokes in daemon mode. */
export function daemonEntry(): string {
  return fileURLToPath(new URL('../index.js', import.meta.url));
}

/**
 * launchd/systemd jobs do NOT inherit the shell PATH — they get a bare
 * /usr/bin:/bin, which excludes where node/npx actually live (Homebrew, nvm).
 * Bake the running node's own bin dir + common install dirs into the job PATH.
 * (Lifted from mailman's ticker-install.ts, which caught this on a live run.)
 */
export function jobPath(nodeBinDir: string = path.dirname(process.execPath)): string {
  if (process.platform === 'win32') return process.env.PATH ?? '';
  return `${nodeBinDir}:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin`;
}

// ── Generators (pure) ────────────────────────────────────────────────────

export function buildLauncherScript(entry: string = daemonEntry()): string {
  // Plain-JS (CJS) launcher — ~/.whatsappman/bin has no package.json, so node
  // treats .js as CJS. Named per-instance so macOS Background Activity shows it.
  const url = pathToFileURL(entry).href;
  return `#!/usr/bin/env node
// Generated by \`whatsappman daemon install\`. Delegates to the daemon entry.
process.argv.splice(2, 0, 'daemon', 'start');
import(${JSON.stringify(url)}).catch((e) => { console.error(e); process.exit(1); });
`;
}

export function buildLaunchdPlist(opts?: {
  label?: string;
  launcher?: string;
  pathStr?: string;
}): string {
  const label = opts?.label ?? launchdLabel();
  const launcher = opts?.launcher ?? launcherPath();
  const pathStr = opts?.pathStr ?? jobPath();
  const outLog = path.join(logsDir(), 'daemon.out.log');
  const errLog = path.join(logsDir(), 'daemon.err.log');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>${label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${launcher}</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key><false/>
    <key>Crashed</key><true/>
  </dict>
  <key>ThrottleInterval</key><integer>10</integer>
  <key>StandardOutPath</key><string>${outLog}</string>
  <key>StandardErrorPath</key><string>${errLog}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key><string>${pathStr}</string>
    <key>HOME</key><string>${os.homedir()}</string>
  </dict>
</dict>
</plist>
`;
}

export function buildSystemdUnit(opts?: { launcher?: string; pathStr?: string }): string {
  const launcher = opts?.launcher ?? launcherPath();
  const pathStr = opts?.pathStr ?? jobPath();
  return `[Unit]
Description=whatsappman WhatsApp daemon
After=network-online.target

[Service]
Type=simple
ExecStart=${launcher}
Restart=on-failure
RestartSec=10
Environment=PATH=${pathStr}
# Hardening (Baileys needs outbound TLS, so AF_INET is allowed).
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=default.target
`;
}

export function buildOpenRcScript(opts?: { launcher?: string; pathStr?: string }): string {
  const launcher = opts?.launcher ?? launcherPath();
  const pathStr = opts?.pathStr ?? jobPath();
  const pidfile = path.join(baseDir(), 'daemon.pid');
  return `#!/sbin/openrc-run
name="whatsappman"
description="whatsappman WhatsApp daemon"
command="${launcher}"
command_background=true
pidfile="${pidfile}"
export PATH="${pathStr}"

depend() {
  need net
}
`;
}

const SCHTASKS_DESC = 'whatsappman WhatsApp daemon';

/** XML-escape a value going into a Task Scheduler element (paths carry `&`, spaces, `"`). */
function xmlEscape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Windows Task Scheduler XML: run the daemon launcher at logon and restart it on
 * failure — the Windows parity for launchd `KeepAlive` / systemd
 * `Restart=on-failure`. The plain `schtasks /Create /SC ONLOGON` command form
 * can't express restart-on-failure, so we register an XML task instead.
 *
 * The action runs the current node with the generated launcher script (the same
 * launcher the posix mechanisms use), so no shebang/PATH assumptions on Windows.
 * Pure + exported for unit testing; the file is materialized in `install()`.
 */
export function buildSchtasksXml(opts?: { nodePath?: string; launcher?: string }): string {
  const command = xmlEscape(opts?.nodePath ?? process.execPath);
  const args = xmlEscape(`"${opts?.launcher ?? launcherPath()}"`);
  return `<?xml version="1.0" encoding="UTF-16"?>
<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">
  <RegistrationInfo>
    <Description>${SCHTASKS_DESC}</Description>
  </RegistrationInfo>
  <Triggers>
    <LogonTrigger>
      <Enabled>true</Enabled>
    </LogonTrigger>
  </Triggers>
  <Principals>
    <Principal id="Author">
      <LogonType>InteractiveToken</LogonType>
      <RunLevel>LeastPrivilege</RunLevel>
    </Principal>
  </Principals>
  <Settings>
    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>
    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>
    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>
    <AllowHardTerminate>true</AllowHardTerminate>
    <StartWhenAvailable>true</StartWhenAvailable>
    <ExecutionTimeLimit>PT0S</ExecutionTimeLimit>
    <RestartOnFailure>
      <Interval>PT1M</Interval>
      <Count>3</Count>
    </RestartOnFailure>
    <Enabled>true</Enabled>
  </Settings>
  <Actions Context="Author">
    <Exec>
      <Command>${command}</Command>
      <Arguments>${args}</Arguments>
    </Exec>
  </Actions>
</Task>
`;
}

/** schtasks CLI args to register the XML task (replaces any existing one via /F). */
export function buildSchtasksCreateArgs(
  xmlPath: string = schtasksXmlPath(),
  taskName: string = schtasksTaskName(),
): string[] {
  return ['/Create', '/TN', taskName, '/XML', xmlPath, '/F'];
}

export interface SupervisorCommand {
  cmd: string;
  args: string[];
}

/**
 * Command(s) to START the daemon **through its installed supervisor**, or null
 * for nohup/none (the caller then falls back to a detached spawn).
 *
 * Why this matters: `startDaemon()` used to always detached-spawn, so a
 * `whatsappman restart` / `update` left the daemon running *outside* launchd/
 * systemd — losing crash auto-restart (KeepAlive / Restart=on-failure) until
 * the next login. Routing start through the supervisor keeps it supervised.
 * Pure + exported for unit testing; executed in cli/daemon-control.ts.
 */
export function supervisorStartPlan(
  mechanism: Mechanism = detectMechanism(),
  host?: string,
): SupervisorCommand[] | null {
  switch (mechanism) {
    case 'launchd': {
      const uid = typeof process.getuid === 'function' ? process.getuid() : 0;
      return [{ cmd: 'launchctl', args: ['kickstart', `gui/${uid}/${launchdLabel(host)}`] }];
    }
    case 'systemd':
      return [{ cmd: 'systemctl', args: ['--user', 'start', 'whatsappman.service'] }];
    case 'openrc':
      return [{ cmd: 'rc-service', args: ['whatsappman', 'start'] }];
    case 'schtasks':
      return [{ cmd: 'schtasks', args: ['/Run', '/TN', schtasksTaskName(host)] }];
    default:
      return null; // nohup / none — caller detached-spawns
  }
}

// ── Paths for the generated OS files ─────────────────────────────────────

/** Per-instance Task Scheduler task name (mirrors the launchd/systemd instance id). */
export function schtasksTaskName(host?: string): string {
  return instanceId(host); // whatsappman-<slug>
}

/** Where the task-definition XML is staged before `schtasks /Create /XML`. */
export function schtasksXmlPath(host?: string): string {
  return path.join(baseDir(), `${instanceId(host)}.xml`);
}

export function launchdPlistPath(host?: string): string {
  return path.join(os.homedir(), 'Library', 'LaunchAgents', `${launchdLabel(host)}.plist`);
}
export function systemdUnitPath(): string {
  return path.join(os.homedir(), '.config', 'systemd', 'user', 'whatsappman.service');
}
export function openRcScriptPath(): string {
  return path.join('/etc', 'init.d', 'whatsappman');
}

// ── Dry-run plan ─────────────────────────────────────────────────────────

export interface InstallPlan {
  mechanism: Mechanism;
  instanceId: string;
  launcherPath: string;
  jobFile?: string;
  jobContent?: string;
  launcherContent: string;
}

export function planInstall(): InstallPlan {
  const mechanism = detectMechanism();
  const launcherContent = buildLauncherScript();
  const base: InstallPlan = {
    mechanism,
    instanceId: instanceId(),
    launcherPath: launcherPath(),
    launcherContent,
  };
  switch (mechanism) {
    case 'launchd':
      return { ...base, jobFile: launchdPlistPath(), jobContent: buildLaunchdPlist() };
    case 'systemd':
      return { ...base, jobFile: systemdUnitPath(), jobContent: buildSystemdUnit() };
    case 'openrc':
      return { ...base, jobFile: openRcScriptPath(), jobContent: buildOpenRcScript() };
    case 'schtasks':
      return { ...base, jobFile: schtasksXmlPath(), jobContent: buildSchtasksXml() };
    default:
      return base; // nohup — no persistent job file
  }
}

// ── Materialize + load / unload ──────────────────────────────────────────

function writeLauncher(): void {
  const p = launcherPath();
  fs.mkdirSync(path.dirname(p), { recursive: true, mode: 0o700 });
  fs.writeFileSync(p, buildLauncherScript(), { mode: 0o700 });
  try {
    fs.chmodSync(p, 0o700);
  } catch {
    /* best-effort */
  }
}

/** Install the OS autostart job. Returns the mechanism used. Mutates system state. */
export function install(): { mechanism: Mechanism; note: string } {
  const mechanism = detectMechanism();
  writeLauncher();

  switch (mechanism) {
    case 'launchd': {
      const plist = launchdPlistPath();
      fs.mkdirSync(path.dirname(plist), { recursive: true });
      fs.writeFileSync(plist, buildLaunchdPlist());
      try {
        execFileSync('launchctl', ['unload', plist], { stdio: 'ignore' });
      } catch {
        /* not loaded yet */
      }
      execFileSync('launchctl', ['load', plist]);
      return { mechanism, note: `loaded launchd agent ${launchdLabel()}` };
    }
    case 'systemd': {
      const unit = systemdUnitPath();
      fs.mkdirSync(path.dirname(unit), { recursive: true });
      fs.writeFileSync(unit, buildSystemdUnit());
      execFileSync('systemctl', ['--user', 'daemon-reload']);
      execFileSync('systemctl', ['--user', 'enable', '--now', 'whatsappman.service']);
      try {
        execFileSync('loginctl', ['enable-linger', os.userInfo().username]);
      } catch {
        /* linger is best-effort; needs privileges on some distros */
      }
      return { mechanism, note: 'enabled systemd --user unit whatsappman.service' };
    }
    case 'openrc': {
      fs.writeFileSync(openRcScriptPath(), buildOpenRcScript(), { mode: 0o755 });
      execFileSync('rc-update', ['add', 'whatsappman', 'default']);
      execFileSync('rc-service', ['whatsappman', 'start']);
      return { mechanism, note: 'added OpenRC service whatsappman' };
    }
    case 'schtasks': {
      // Task Scheduler's /Create /XML wants a UTF-16LE file (with BOM); it
      // rejects UTF-8. Stage the XML, then register it at logon with restart.
      const xmlPath = schtasksXmlPath();
      const BOM = String.fromCharCode(0xfeff); // UTF-16LE byte-order mark schtasks requires
      fs.writeFileSync(xmlPath, Buffer.from(BOM + buildSchtasksXml(), 'utf16le'));
      execFileSync('schtasks', buildSchtasksCreateArgs(xmlPath));
      return { mechanism, note: `registered Task Scheduler task ${schtasksTaskName()} (at logon, restart on failure)` };
    }
    default:
      return {
        mechanism,
        note: 'no persistent autostart configured (nohup) — start the daemon manually with `whatsappman start`',
      };
  }
}

/** Remove the OS autostart job. Mutates system state. */
export function uninstall(): { mechanism: Mechanism } {
  const mechanism = detectMechanism();
  try {
    switch (mechanism) {
      case 'launchd': {
        const plist = launchdPlistPath();
        try {
          execFileSync('launchctl', ['unload', plist], { stdio: 'ignore' });
        } catch {
          /* ignore */
        }
        fs.rmSync(plist, { force: true });
        break;
      }
      case 'systemd':
        try {
          execFileSync('systemctl', ['--user', 'disable', '--now', 'whatsappman.service'], {
            stdio: 'ignore',
          });
        } catch {
          /* ignore */
        }
        fs.rmSync(systemdUnitPath(), { force: true });
        break;
      case 'openrc':
        try {
          execFileSync('rc-update', ['del', 'whatsappman', 'default'], { stdio: 'ignore' });
        } catch {
          /* ignore */
        }
        fs.rmSync(openRcScriptPath(), { force: true });
        break;
      case 'schtasks':
        try {
          execFileSync('schtasks', ['/Delete', '/TN', schtasksTaskName(), '/F'], { stdio: 'ignore' });
        } catch {
          /* ignore */
        }
        fs.rmSync(schtasksXmlPath(), { force: true });
        break;
    }
  } catch {
    /* best-effort cleanup */
  }
  fs.rmSync(launcherPath(), { force: true });
  return { mechanism };
}

/** Is the OS autostart job currently present on disk? */
export function isInstalled(): boolean {
  switch (detectMechanism()) {
    case 'launchd':
      return fs.existsSync(launchdPlistPath());
    case 'systemd':
      return fs.existsSync(systemdUnitPath());
    case 'openrc':
      return fs.existsSync(openRcScriptPath());
    case 'schtasks':
      // The task lives in Task Scheduler, not on disk — query it directly.
      try {
        execFileSync('schtasks', ['/Query', '/TN', schtasksTaskName()], { stdio: 'ignore' });
        return true;
      } catch {
        return false;
      }
    default:
      return false;
  }
}
